name: CI Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install Python Dependencies
      run: |
        cd backend
        pip install -r requirements.txt
        # Add linters later, e.g., pip install ruff black
        # ruff check .
        # black --check .

    - name: Set up Node.js 18
      uses: actions/setup-node@v4
      with:
        node-version: '18'

    - name: Install Node.js Dependencies
      run: |
        cd frontend
        npm install
        # Add linters later
        # npm run lint
